packages:
  - "apps/*"
  - "packages/*"
  - "!packages/safe-smart-account" # Exclude safe-smart-account package (development only)
  - "!app/envio-indexer" # Exclude envio-indexer app (no time to implement it properly)
